#!/bin/bash

project_number=291 #DanERP Pilot
platform=9 #Java

commit_log_dir="/home/cryogenick/Dev/Dyno_hack/commit_log"

if [ ! -d $commit_log_dir ]; then
    mkdir $commit_log_dir
fi

commit_log_file="$commit_log_dir/${project_number}_$platform"

latest_commit_message=$(git log -1 --pretty=%s)

if [ -e $commit_log_file ]; then
    if [ -s $commit_log_file ]; then
        echo -n " | " >> "$commit_log_file"
    fi
fi

echo -n "$latest_commit_message" >> "$commit_log_file"
